export { default as Layout } from './Layout'
export { default as Home } from './Home'
export { default as Services } from './Services'
export { default as Portfolio } from './Portfolio'
export { default as Contact } from './Contact'